language: java
jdk:
- oraclejdk8
addons:
  sonarqube: true
env:
  global:
  #SONAR_GITHUB_TOKEN
  - secure: bDjxrFFCbzDZyTIv86rCs9PQyzFufawt+qIFjH4H6Qm09U4ZymdkrqQ/NLWTKqRZ0KYQdfZoyd9HjHr7PP+1K6EY8eBJ66kUU/0nY3S9q+agPJffTDhcKf+Cx2Bh0GCZWY0Mru2tq79jcp+0TjChi9Wh5xigNbr9CuATpYXUkwsumhOZSgj0W5utb9vZ2/SPR5+Mbz/JXN/sf27G7RyIvCkYZJutuklb9ycp66SaDH1f61Q/DHmnLvS8Md0H7Lo9QtVf/vBJMWyvzJA3bKhNCpyIM+QWYli4vp4hfOzMaTm5e6anZ8KK9E9nhV6VLSs9oosGuKynOFxwo/KYyFIt0VebhfCtCTDgD4XYLVV/354qY+FUmnj4pybWItAqrc/NdS1d+UiMCpkWsV5EKUYX+SQfDPgdPcZwmQ9ttQOFK7my+xBhSD9srcL8EatuYBCchydOACyRnY8b/puPERvn8y04SaLK9C307HHnTc9igVJwOMVU/dY6n3rlSwSdXeli3oQRPzNq/xyiGUW6RbmK55L8RDzx2zuOOBgojdafhX+BKc+xXRzpGeGd2qfd3v6HFx9+7XPkzYk2FMYtLXGTvwwwquGsIvNqsiCdXZK+Wt/3C8YP9/ob1cJwBXdRaENEWN1LLjoSe895ly9Vg3j7+nUjrQocWC/tCuSnhsuoljM=
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.login=$SONAR_GITHUB_TOKEN
